"use client";
import Link from "next/link";
import { DemoProviderThread } from "@/app/components/DemoProviderThread";
import { requestEventId } from "@/lib/customer-demo/events";
import { EventHubSummary } from "./EventHubSummary";
import { useEffect, useState } from "react";
import { EventPartsSummary } from "@/app/discover/components/EventParts";
import { loadDemoQuoteRequests, opportunityStatus, updateDemoOpportunity, type DemoQuoteRequest } from "@/lib/event-intelligence/demo-quotes";
import { formatMoney, formatTime } from "@/lib/utils/format";

export function RequestWorkspace({ requestId }: { requestId?: string }) {
  const [requests, setRequests] = useState<DemoQuoteRequest[]>([]);
  const [ready, setReady] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => {
    const refresh = () => { setRequests(loadDemoQuoteRequests()); setReady(true); };
    queueMicrotask(refresh);
    window.addEventListener("arivvio:customer-changed", refresh); window.addEventListener("focus", refresh); window.addEventListener("storage", refresh);
    return () => { window.removeEventListener("arivvio:customer-changed", refresh); window.removeEventListener("focus", refresh); window.removeEventListener("storage", refresh); };
  }, []);
  const request = requests.find(item => item.id === requestId);
  return <section className="mx-auto max-w-5xl px-4 py-10 sm:px-8">
    <p className="text-xs uppercase tracking-widest ui-muted">Your saved event requests</p>
    <h1 className="mt-3 text-3xl font-semibold">{request?.event.name ?? (requestId ? "Event request" : "Keep your event together.")}</h1>
    <p className="mt-3 text-sm leading-6 ui-muted">Saved in this browser only. Demo responses are simulations. No vendor receives a message, and no booking or payment is made.</p>
    <div className="my-6 flex flex-wrap gap-3"><Link className="hub-button" href="/account/demo">Demo Account</Link>{request && <Link className="hub-button" href={`/account/demo/events/${encodeURIComponent(requestEventId(request))}`}>Event Hub</Link>}<Link className="hub-button" href="/requests">All saved requests</Link><Link className="hub-button" href="/discover">Open planner</Link></div>
    {!ready ? <p role="status">Loading saved requests…</p> : requestId && !request ? <div className="hub-card p-6"><h2 className="text-xl font-semibold">Request unavailable here</h2><p className="mt-2 ui-muted">Open the browser where you submitted it. Demo requests do not sync across devices.</p><Link className="hub-button mt-4" href="/marketplace?entryMode=browse">Explore Marketplace</Link></div> : request ? <>
      <EventHubSummary request={request} />
      <section id="event-details" className="hub-card p-5 sm:p-7"><p className="text-xs ui-muted">Request {request.id.slice(-8)} · Saved {new Date(request.createdAt).toLocaleDateString()}</p><h2 className="mt-3 text-xl font-semibold">Event overview</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2">{[["Date & overall time", `${request.event.date || "Date to confirm"} · ${formatTime(request.event.startTime)} – ${formatTime(request.event.endTime)}`], ["Location", request.event.location || "Location to confirm"], ["Guests", String(request.event.guestCount)], ["Overall budget", formatMoney(request.event.budget)]].map(([label, value]) => <div key={label}><dt className="text-xs uppercase tracking-wider ui-muted">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>)}</dl>{request.event.requirements && <p className="mt-5 whitespace-pre-wrap text-sm ui-muted">{request.event.requirements}</p>}<div className="mt-6"><EventPartsSummary stages={request.event.profile?.stages ?? []} defaults={request.event} /></div></section>
      <section id="provider-requests" className="mt-6"><h2 className="text-xl font-semibold">Your provider requests</h2><p className="mt-2 text-sm ui-muted">Compare requested estimates with demo responses. Reviewing a quote does not accept it or reserve a provider.</p><div className="mt-4 grid gap-4 md:grid-cols-2">{request.opportunities.map(item => <article className="hub-card p-5" key={item.id}><p className="text-xs ui-muted">{opportunityStatus(item)}</p><h3 className="mt-2 text-lg font-semibold">{item.providerName}</h3><p className="mt-1 text-sm">{item.service}</p><p className="mt-2 text-sm ui-muted">{formatTime(item.startTime)} – {formatTime(item.endTime)}</p><p className="mt-1 text-sm ui-muted">{item.stageIds.length ? request.event.profile?.stages.filter(part => item.stageIds.includes(part.id)).map(part => part.label).join(" + ") : "Entire event"}</p><p className="mt-4 text-sm">Requested estimate: {formatMoney(item.estimate)}</p>{item.response && <div className="mt-4 rounded-xl ui-soft p-4"><p className="font-semibold">{item.response.status === "quoted" ? `Demo quote: ${formatMoney(item.response.price)}` : "Provider declined in demo"}</p><p className="mt-2 whitespace-pre-wrap text-sm ui-muted">{item.response.note || "No additional details."}</p><p className="mt-2 text-xs ui-muted">Recorded {new Date(item.response.at).toLocaleString()}</p></div>}{item.response?.status === "quoted" && !item.reviewedAt && <button className="hub-button mt-4" onClick={() => { try { updateDemoOpportunity(request.id, item.id, current => ({ ...current, reviewedAt: new Date().toISOString() })); setRequests(loadDemoQuoteRequests()); setError(""); } catch { setError("Unable to save. Check browser storage and try again."); } }}>Mark quote reviewed</button>}{item.providerId === "49" && <Link href="/vendor/demo#Inquiries" className="mt-4 block text-sm underline">Try this inquiry in Vendor Demo</Link>}<DemoProviderThread request={request} opportunity={item} /></article>)}</div></section>
      {request.message && <section className="hub-card mt-6 p-5"><h2 className="font-semibold">Your request message</h2><p className="mt-2 whitespace-pre-wrap text-sm ui-muted">{request.message}</p></section>}
      <section className="mt-6 rounded-2xl ui-soft p-5"><h2 className="font-semibold">Bookings</h2><p className="mt-2 text-sm ui-muted">No booking is created by this demo request. Quote acceptance, contracts and payments are not connected yet.</p></section>
    </> : requests.length ? <div className="grid gap-4 sm:grid-cols-2">{requests.map(item => <Link href={`/requests/${item.id}`} className="hub-card block p-6" key={item.id}><p className="text-xs ui-muted">{item.event.date || "Date to confirm"} · {item.event.guestCount} guests</p><h2 className="mt-2 text-xl font-semibold">{item.event.name}</h2><p className="mt-3 text-sm ui-muted">{item.opportunities.length} provider requests · {item.opportunities.filter(provider => provider.response).length} demo responses</p><p className="mt-4 text-sm font-semibold">Open event request →</p></Link>)}</div> : <div className="hub-card p-6"><h2 className="text-xl font-semibold">Your next occasion starts here.</h2><p className="mt-2 ui-muted">Choose providers in Marketplace and submit a demo request. Its event details, services and responses will stay together here.</p><Link className="hub-button mt-5" href="/marketplace?entryMode=browse">Find your event team</Link></div>}
    {error && <p role="alert" className="mt-4">{error}</p>}
  </section>;
}
